version: '3'
services:
  database_dev:
    image: 'postgres:latest'
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./env/prod.env
    volumes:
      - ./db-dev/:/var/lib/postgresql/data/
  database_test:
    image: 'postgres:latest'
    restart: always
    ports:
      - 5433:5432
    env_file:
      - ./env/test.env
    volumes:
      - ./db-test/:/var/lib/postgresql/data/
  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
