### Signup User
POST http://localhost:3001/api/user/signup-email-and-password HTTP/1.1
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "P@ssword1",
    "firstName": "Foo",
    "lastName": "Bar",
    "role": "USER_DEFAULT"
}